#! /bin/sh

### BEGIN INIT INFO
# Provides:          
# Required-Start:    $pacoda-proxy $syslog
# Required-Stop:     $pacoda-proxy
# Should-Start:      
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: starts all users applications defined thier pacoda state files
# Description:       each user may have a pacoda state that will include any number of
#                    pacoda applications and this utility will autostart all available states.
### END INIT INFO

# /etc/init.d/pacoda: start and stop all pacoda user state applications

exitval=0

case "$1" in
	start)
		pacoda state reload all
		exitval=$?
	;;
	stop)
		pacoda state unload all
		exitval=$?
	;;
	*)
		echo "Usage: /etc/init.d/pacoda {start|stop}"
		exit 1
	;;
esac

exit $exitval

