#! /bin/sh
# /etc/init.d/zimr
#

### BEGIN INIT INFO
# Provides:          zimr
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $networking $named $time
# Should-Stop:       $networking $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts all users applications defined thier zimr state files
# Description:       each user may have a zimr state that will include any number of
#                    zimr applications and this utility will autostart all available states.
### END INIT INFO

exitval=0

case "$1" in
	start)
		zimr start all users -not-stopped
	;;
	restart)
		zimr restart all users
		#exitval=$?
	;;
	stop)
		zimr stop all users
		#exitval=$?
	;;
	remove)
		zimr remove all users
		#exitval=$?
	;;
	*)
		echo "Usage: /etc/init.d/zimr {restart|stop|remove}"
		exit 1
	;;
esac

exit $exitval

