#! /bin/sh
# /etc/init.d/zimrd
#

### BEGIN INIT INFO
# Provides:          zimrd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $networking $named $time
# Should-Stop:       $networking $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: virtual http host proxy
# Description:       zimrd is a specialized http proxy to route
#                    http(s) requests to internally or externally connected applications.
### END INIT INFO


exitval=0

case "$1" in
	start)
		zimrd start
		#exitval=$?
	;;
	stop)
		zimrd stop
		#exitval=$?
	;;
	restart)
		zimrd restart
		#exitval=$?
	;;
	*)
		echo "Usage: /etc/init.d/zimrd {start|stop}"
		exit 1
	;;
esac

exit $exitval
