#! /bin/sh
# /etc/init.d/zimr-proxy
#

### BEGIN INIT INFO
# Provides:          zimr-proxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $networking $named $time
# Should-Stop:       $networking $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: virtual http host proxy
# Description:       zimr-proxy is a specialized http proxy to route
#                    http(s) requests to internally or externally connected applications.
### END INIT INFO


exitval=0

case "$1" in
	start)
		zimr-proxy start
		#exitval=$?
	;;
	stop)
		zimr-proxy stop
		#exitval=$?
	;;
	restart)
		zimr-proxy restart
		#exitval=$?
	;;
	*)
		echo "Usage: /etc/init.d/zimr-proxy {start|stop}"
		exit 1
	;;
esac

exit $exitval
